"~/.vimrc
set nocompatible              " be iMproved, required
syntax on
set expandtab
set tabstop=3
set wildmenu
set wildmode=longest:list,full
set wildignorecase
set smartcase
set secure
set nowrap
let mapleader = ","
set colorcolumn=120
set incsearch
set autoindent

" clang-format binding
map <C-K> :py3f ~/Tools/clang-format.py<cr>

"fix for slow response after Esc, O
set timeout timeoutlen=3000 ttimeoutlen=100

" let me switch away from modified buffers
set hidden
"fly between buffers
nnoremap <leader>l :ls<CR>:b<Space>

"Syntax highlighting for Snakefiles
au BufNewFile,BufRead Snakefile set syntax=snakemake
au BufNewFile,BufRead *.smk set syntax=snakemake

" LateX mode
set wrap
nnoremap <leader>m :w<CR>:!make<CR>
