"--- Vundle config start ---
set nocompatible
filetype off

"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'wincent/command-t'
Plugin 'bling/vim-bufferline'
Plugin 'tpope/vim-fugitive'

call vundle#end()
filetype plugin indent on
"--- Vundle config end ---

syntax enable
set expandtab
set tabstop=3
set wildmenu
set wildmode=longest:list,full
set wildignorecase
set ignorecase
set smartcase
set incsearch
set hlsearch
set secure
set nowrap
set colorcolumn=120
set autoindent
set list
set listchars=tab:!·,trail:·
set autowrite
let mapleader = ","

" clang-format binding
map <C-K> :py3f ~/Tools/clang-format.py<cr>

"fix for slow response after Esc, O
set timeout timeoutlen=3000 ttimeoutlen=100

" let me switch away from modified buffers
set hidden
"fly between buffers
nnoremap <leader>l :ls<CR>:b<Space>
nnoremap <leader>n :bn<CR>
nnoremap <leader>p :bp<CR>

"Syntax highlighting for Snakefiles
au BufNewFile,BufRead Snakefile set syntax=snakemake
au BufNewFile,BufRead *.smk set syntax=snakemake

"Airline
let g:airline_powerline_fonts = 1
let g:airline_theme = "base16_bright"

"LateX mode
set wrap
set noautoindent

" ---- For safekeeping ----
""Better fuzzy search (i.e. built-in ctrlP)
"nnoremap <leader>p :e **/*
"nnoremap <leader>v :vsplit **/*
"nnoremap <leader>s :split **/*
